services:
  - type: web
    name: phishai-backend
    env: python
    branch: main
    plan: free

    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHONPATH
        value: .
      - key: ENV
        value: production
